from typing import Any, Dict, Tuple
import torch
import torch.nn as nn

# Purely relative imports pointing to registry and base class layout
from ..criterions_manager import CriterionsManager
from ..base_criterion import MSIBaseCriterion


@CriterionsManager.register_criterion("MSELoss")
class MSIMSELoss(MSIBaseCriterion):
    """
    Mean Squared Error (MSE) loss strategy for grid-x-axis spectral reconstruction.

    This criterion computes the pixel-by-pixel squared discrepancies between the 
    original binned mass spectrometry intensity vectors and the reconstructed profiles 
    generated by the decoder network layer.
    """

    def __init__(self, reduction: str = "mean") -> None:
        """
        Initializes the underlying PyTorch MSE loss module block.

        :param reduction: Specifies the reduction scheme to apply to output tensors: 
                          'mean', 'sum', or 'none'. Defaults to 'mean'.
        :type reduction: str
        """
        super().__init__()
        
        # Cache parameter definitions snapshot for future schematic serialization
        self._config = {"reduction": reduction}
        
        # Core underlying standard PyTorch cost function deployment
        self.loss_fn = nn.MSELoss(reduction=reduction)

    @property
    def requires_reconstruction(self) -> bool:
        """
        Signals that this loss block requires full grid-x-axis spectral reconstruction arrays.

        :return: Always returns True.
        :rtype: bool
        """
        return True

    @property
    def requires_projection(self) -> bool:
        """
        Signals that this loss block does not utilize contrastive projection head coordinates.

        :return: Always returns False.
        :rtype: bool
        """
        return False

    def forward(
        self,
        model_outputs: Dict[str, torch.Tensor],
        batch_data: Tuple[torch.Tensor, torch.Tensor],
        **kwargs: Any
    ) -> torch.Tensor:
        """
        Evaluates the mean squared reconstruction error between target arrays.

        :param model_outputs: Dictionary mapping active tensors generated by the network forward pass.
        :type model_outputs: dict[str, torch.Tensor]
        :param batch_data: Aligned variables tuple matching (spatial_indices, binned_spectra) from the loader.
        :type batch_data: tuple(torch.Tensor, torch.Tensor)
        :return: Singular scalar loss tensor tracking backpropagation tracking gradients.
        :rtype: torch.Tensor
        :raises KeyError: If the required 'reconstruction' key is absent from the model outputs map.
        """
        # Data dependency validation
        if "reconstruction" not in model_outputs:
            raise KeyError(
                "The 'reconstruction' tensor token is missing from model outputs map. "
                "Ensure that the decoder module graph is active during this training pass stage."
            )

        # Unpack targets from batch inputs
        ## spatial_indices token is skipped as MSE operates purely on numerical spectrum definitions
        _, original_spectra = batch_data
        
        # Extract evaluated predictions from the architecture map
        reconstructed_spectra = model_outputs["reconstruction"]

        # Compute and return the mathematical reduction error matrix score
        return self.loss_fn(reconstructed_spectra, original_spectra)