"""
Abstract base module establishing the definitive mathematical contract for all MSI loss functions.
"""

from abc import ABC, abstractmethod
from typing import Any, Dict, Tuple
import torch
import torch.nn as nn

from ...models.datasets.base_dataset import MSIBaseDataset
from ...utils.logger import get_custom_logger

# Logger initialization
logger = get_custom_logger(__name__)


class MSIBaseCriterion(nn.Module, ABC):
    """
    Abstract Base Class defining operational frameworks and lifecycle hooks for MSI cost functions.
    """

    def __init__(self) -> None:
        """
        Initializes the base criterion abstraction layer.
        """
        super().__init__()
        self._config: Dict[str, Any] = {}

    def GetConfig(self) -> Dict[str, Any]:
        """
        Retrieves serialized parameters mapping snapshots required to reproduce the criterion state.

        :return: Internal dictionary containing hyperparameter definitions.
        :rtype: Dict[str, Any]
        """
        return self._config

    def on_phase_start(self, model: nn.Module, dataset: MSIBaseDataset, transient_cache: Dict[str, Any]) -> None:
        """
        Optional execution lifecycle hook triggered once before the phase epoch sequence loop initiates.

        Useful for heavy pre-computations such as peak-picking or initializing shared statistical arrays.

        :param model: The compiled master architecture model graph currently being optimized.
        :type model: nn.Module
        :param dataset: Bound dataset instance containing raw target spectra profiles.
        :type dataset: MSIBaseDataset
        :param transient_cache: Mutable global scratchpad tracking state variables across the active session.
        :type transient_cache: Dict[str, Any]
        """
        pass

    def on_batch_start(self, batch_data: Tuple[torch.Tensor, ...], transient_cache: Dict[str, Any]) -> Tuple[torch.Tensor, ...]:
        """
        Optional execution lifecycle hook triggered for every step batch stream iteration before forward calls.

        Enables on-the-fly computational operations like chemical noise augmentations on the GPU.

        :param batch_data: Tensors krotka returned from the active data loader.
        :type batch_data: Tuple[torch.Tensor, ...]
        :param transient_cache: Mutable global scratchpad tracking state variables across the active session.
        :type transient_cache: Dict[str, Any]
        :return: Transformed or untouched batch variables aligned to data specifications.
        :rtype: Tuple[torch.Tensor, ...]
        """
        return batch_data

    @abstractmethod
    def forward(
        self,
        model_outputs: Dict[str, torch.Tensor],
        batch_data: Tuple[torch.Tensor, ...],
        **kwargs: Any
    ) -> torch.Tensor:
        """
        Computes the target objective mathematical loss matrix score using extracted forward tensors.

        :param model_outputs: Collection mapping outputs generated by the active model forward pass.
        :type model_outputs: Dict[str, torch.Tensor]
        :param batch_data: Variables tuple matching data loader outputs.
        :type batch_data: Tuple[torch.Tensor, ...]
        :return: Singular scalar tensor containing tracking gradients.
        :rtype: torch.Tensor
        """
        pass