"""Extensible sampling strategies for synthetic spectra."""

from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import Any, Dict, Mapping, Type

import numpy as np

from .sources import SyntheticPeakSource
from ...utils.module_search import discover_modules
from ...utils.printing import extract_component_signatures
from ...utils.validators import resolve_component, validate_subclass


@dataclass(frozen=True)
class SyntheticSamplingPlanEntry:
    """Specify one synthetic sampling strategy and its exact epoch count.

    :param strategy: Registered strategy identifier.
    :param count: Number of samples generated by this strategy per epoch.
    :param parameters: Strategy-specific immutable settings.
    :param label_targets: Override the phase-level target masking policy.  A
        value of ``False`` retains the generated spectrum but masks all
        supervised targets, enabling reconstruction-only samples.
    """

    strategy: str
    count: int
    parameters: Mapping[str, Any] = field(default_factory=dict)
    label_targets: bool | None = None

    def __post_init__(self) -> None:
        if not isinstance(self.strategy, str) or not self.strategy:
            raise ValueError("sampling strategy must be a nonempty string.")
        if isinstance(self.count, bool) or not isinstance(self.count, int) or self.count < 1:
            raise ValueError("sampling count must be a positive integer.")
        if not isinstance(self.parameters, Mapping):
            raise ValueError("sampling parameters must be a mapping.")
        if self.label_targets is not None and not isinstance(self.label_targets, bool):
            raise ValueError("sampling label_targets must be a boolean or null.")
        object.__setattr__(self, "parameters", dict(self.parameters))

    @property
    def output_count(self) -> int:
        """Return generated samples after candidate-permutation expansion.

        ``count`` is the number of base candidate draws. For
        ``candidate_permuted``, ``parameters.permutations`` specifies the
        number of independently weighted variants emitted for every draw.
        Other strategies preserve their historical ``count`` semantics.
        """
        if self.strategy != "candidate_permuted":
            return self.count
        permutations = self.parameters.get("permutations", 1)
        if (
            isinstance(permutations, bool)
            or not isinstance(permutations, int)
            or permutations < 1
        ):
            raise ValueError("candidate_permuted.permutations must be a positive integer.")
        return self.count * permutations

    @classmethod
    def from_value(cls, value: "SyntheticSamplingPlanEntry | Mapping[str, Any]") -> "SyntheticSamplingPlanEntry":
        """Normalize an API or YAML sampling-plan entry."""
        if isinstance(value, cls):
            return value
        if not isinstance(value, Mapping):
            raise ValueError("Every sampling_plan entry must be a mapping.")
        raw = dict(value)
        strategy = raw.pop("strategy", raw.pop("mode", None))
        count = raw.pop("count", None)
        parameters = raw.pop("parameters", {})
        label_targets = raw.pop("label_targets", None)
        if raw:
            raise ValueError(f"Unsupported sampling_plan keys: {sorted(raw)}.")
        return cls(strategy=strategy, count=count, parameters=parameters, label_targets=label_targets)


@dataclass(frozen=True)
class SyntheticComponent:
    """One generated peak with an optional target-column identity and weight."""

    center: int
    label_index: int | None
    intensity_weight: float = 1.0


@dataclass(frozen=True)
class SyntheticSampleDefinition:
    """Describe peaks, provenance, and target availability before rendering."""

    components: tuple[SyntheticComponent, ...]
    label_targets: bool
    metadata: Mapping[str, Any] = field(default_factory=dict)


@dataclass(frozen=True)
class SyntheticSamplingContext:
    """Static data available to every strategy in a pretraining phase."""

    source: SyntheticPeakSource
    eligible_labels: tuple[int, ...]
    background_bins: np.ndarray
    default_max_peaks: int


class SyntheticSamplingStrategy(ABC):
    """Generate peak components for one synthetic training example."""

    name: str

    @abstractmethod
    def sample(
        self,
        rng: np.random.Generator,
        context: SyntheticSamplingContext,
        *,
        label_targets: bool,
    ) -> SyntheticSampleDefinition:
        """Return one sample definition using only the supplied local RNG."""


class SyntheticSamplingManager:
    """Register, discover, document, and resolve synthetic sampling strategies."""

    _REGISTRY: Dict[str, Type[SyntheticSamplingStrategy]] = {}

    @classmethod
    def register_strategy(cls, name: str):
        """Register one concrete sampling strategy under a configuration name.

        :param name: Stable configuration identifier for the strategy.
        :type name: str
        :return: Decorator validating and recording the implementation class.
        :rtype: Callable
        """
        if not isinstance(name, str) or not name:
            raise ValueError("Synthetic sampling strategy names must be nonempty strings.")

        def decorator(
            subclass: Type[SyntheticSamplingStrategy],
        ) -> Type[SyntheticSamplingStrategy]:
            validate_subclass(subclass, SyntheticSamplingStrategy, "SyntheticSamplingRegistry")
            cls._REGISTRY[name] = subclass
            return subclass

        return decorator

    @classmethod
    def get_strategy(
        cls,
        name: Any,
        **kwargs: Any,
    ) -> SyntheticSamplingStrategy:
        """Instantiate a registered strategy from its configuration identifier."""
        cls.discover_strategies()
        return resolve_component(
            target=name,
            registry=cls._REGISTRY,
            component_type="Synthetic sampling strategy",
            expected_type=SyntheticSamplingStrategy,
            **kwargs,
        )

    @classmethod
    def get_available_strategies(cls) -> Dict[str, Dict[str, Any]]:
        """Return strategy docstrings and constructor settings for configuration UIs."""
        cls.discover_strategies()
        return extract_component_signatures(cls._REGISTRY)

    @classmethod
    def discover_strategies(cls) -> None:
        """Import strategy modules so their registration decorators execute."""
        discover_modules(f"{__package__}.strategies")


def register_sampling_strategy(name: str):
    """Return the standard decorator for a synthetic sampling strategy."""
    return SyntheticSamplingManager.register_strategy(name)


def get_sampling_strategy(name: Any, **kwargs: Any) -> SyntheticSamplingStrategy:
    """Resolve a configured synthetic sampling strategy."""
    return SyntheticSamplingManager.get_strategy(name, **kwargs)


def sampling_strategy_names() -> tuple[str, ...]:
    """Return discovered synthetic sampling identifiers in deterministic order."""
    SyntheticSamplingManager.discover_strategies()
    return tuple(sorted(SyntheticSamplingManager._REGISTRY))
